"use client";

import { motion, AnimatePresence } from "framer-motion";

interface Props {
  isOpen: boolean;
  onClose: () => void;
}

const MOCK_SUMMARY = `## Thread Summary

**Core Question:** How does culture shape personality, and can we meaningfully study this relationship?

### Key Arguments

1. **The Big Five is structurally universal but culturally variable** — Factor structure holds across cultures, but mean trait levels differ significantly. The methodological challenge is disentangling trait differences from response-style differences.

2. **Biology and culture are co-constitutive** — Rather than a nature vs. nurture split, genes influence cultural niche-seeking while culture shapes gene expression through epigenetics. Bronfenbrenner's ecological model captures the nested relationship.

3. **Individualism/Collectivism is useful as a lens but dangerous as a category** — Markus & Kitayama's framework is valuable when applied contextually, but becomes reductive when used to essentialize entire cultures. Variation within cultures often exceeds variation between them.

4. **"Asia" is not a monolith** — Korean jeong, Japanese amae, and Chinese guanxi represent genuinely distinct psychological constructs, not just different labels for "collectivism."

5. **Culture is ontologically real but processual** — Like a traffic jam, culture is an emergent property with genuine causal power that cannot be reduced to individual behavior.

### Open Questions
- Can indigenous psychologies be compared without reducing them to Western frameworks?
- Is "culture" best understood as a collection of shared narratives?
- How do we study cultural influence without WEIRD methodological bias?

### Sources Cited
McCrae & Terracciano (2005), Vygotsky (1978), Bronfenbrenner (1979), Markus & Kitayama (1991), Henrich et al. (2010), Nisbett (2003), Stanford Encyclopedia of Philosophy`;

export function SummarySheet({ isOpen, onClose }: Props) {
  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/60 z-50"
            onClick={onClose}
          />
          <motion.div
            initial={{ y: "100%" }}
            animate={{ y: 0 }}
            exit={{ y: "100%" }}
            transition={{ type: "spring", damping: 30, stiffness: 300 }}
            className="fixed bottom-0 left-0 right-0 z-50 bg-zinc-900 border-t border-zinc-700 rounded-t-2xl max-h-[85vh] flex flex-col"
          >
            <div className="flex justify-center pt-2 pb-1">
              <div className="w-10 h-1 rounded-full bg-zinc-700" />
            </div>
            <div className="flex items-center justify-between px-4 py-2 border-b border-zinc-800">
              <div className="flex items-center gap-2">
                <span className="text-lg">✨</span>
                <span className="text-sm font-medium text-zinc-300">AI Summary</span>
              </div>
              <button onClick={onClose} className="text-sm text-zinc-500">
                Close
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-4">
              <div className="prose prose-invert prose-sm max-w-none text-zinc-300 prose-headings:text-zinc-100 prose-h2:text-base prose-h3:text-sm prose-strong:text-zinc-200 prose-li:my-0.5">
                <div className="bg-gradient-to-r from-purple-900/20 to-blue-900/20 border border-purple-800/30 rounded-lg p-3 mb-4">
                  <p className="text-xs text-purple-300 mb-0">
                    Generated by AI based on 33 messages across 3 forks
                  </p>
                </div>
                {MOCK_SUMMARY.split("\n").map((line, i) => {
                  if (line.startsWith("## "))
                    return (
                      <h2 key={i} className="text-base font-bold mt-4 mb-2">
                        {line.replace("## ", "")}
                      </h2>
                    );
                  if (line.startsWith("### "))
                    return (
                      <h3 key={i} className="text-sm font-semibold mt-3 mb-1">
                        {line.replace("### ", "")}
                      </h3>
                    );
                  if (line.startsWith("- "))
                    return (
                      <p key={i} className="text-sm ml-4 my-1">
                        {line}
                      </p>
                    );
                  if (line.match(/^\d\./))
                    return (
                      <p key={i} className="text-sm my-1">
                        {line}
                      </p>
                    );
                  if (line.trim() === "") return <div key={i} className="h-2" />;
                  return (
                    <p key={i} className="text-sm">
                      {line}
                    </p>
                  );
                })}
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
